### ISSUE TITLE
Switch Networks

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-wallet#170]
## Story

As a user participating in Stake Wars, I want to be able to switch networks in the wallet, so I can create and manage my Stake Wars accounts.

## Acceptance Criteria

- [ ] The current network is displayed in a dropdown
- [ ] User can view and select available networks in the dropdown
  - [ ] User is redirected to the selected network's URL
- [ ] If not on testnet, banner is displayed with "You are using X net"
- [ ] Mobile ok
- [ ] Tested

## Assets

- Designs needed: @jakestutzman 
- [Mockup](https://drive.google.com/open?id=11eJN6UNWZGgWM5M856Rq7leqlcSby2zA)

## NOTES

-

**Comment by vgrichina** [comment]
I think we shouldn't do network selection dropdown. It's not something that users normally need to do. Therefore its distraction.
And it doesn't even solve problem of selecting network anyway, because the app itself need to talk to different network as well, so changing it in wallet is confusing.

Banner idea is good though, I think we just need to have multiple sub-domains and banners on non-MainNet networks.

**Comment by kcole16** [comment]
Agreed that the average user should never need to consider it. 

How about putting the dropdown on the "Profile" page? Or even adding an "Advanced Settings" (this is what Coinbase Wallet and other do).

I do think devs should have access to it somewhere, so they don't need to remember the URLs for the networks.

**Comment by vgrichina** [comment]
Devs need to remember the URLs for the networks anyway, as they need to specify these URLs when connecting app to wallet.

**Comment by vgrichina** [comment]
I think might be useful to have a status page with the list of all available wallets / RPC endpoints and their status. So that it can be starting point for devs.

**Comment by kcole16** [comment]
Closing this and opening another issue to add the TestNet banner and update the URL
