### ISSUE TITLE
Email-based Recovery

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-wallet#231]
## Story

As a user creating a new NEAR account via the wallet, I want to setup a low effort form of recovery, so I can continue using the app I started in while still having some safety.

## Acceptance Criteria

Setup Recovery
- [x] User can toggle between email recovery and phone recovery on "Choose Recovery" page
- [x] User can enter their email and select "Protect Account"
  - [x] User is redirected to "Confirm Recovery Setup" page
- [x] User receives an email with instructions and "Recover Account" button (see copy in Notes)

Verify Recovery
- [x] User can view their email address and description of process (See Notes)
- [x] User can select "Confirm" to complete signup flow and be redirected
- [x] User can return to the previous step to re-enter email or resend (See Notes)

Email
- [x] Button URL includes a recovery key in the args
- [x] After clicking button, user is redirected to the recovery flow

Recovery Flow
- [x] Full access key is created by a TX, key is stored in user's localStorage
- [x] User is redirected to "Restore Account" page (design and copy in Notes)
  - [x] Clicking `Continue` saves account in localStorage, user is redirected to "Summary"
  - [x] Clicking `Copy URL` saves URL to clipboard
- [x] Mobile ok
- [x] Tested

## Assets

- [Designs](https://projects.invisionapp.com/share/9ES2D82U8GB#/screens/392906890)
- [User flows](https://docs.google.com/document/d/1uDNhjv65QaGG-5qWM3gju9LCRqNFhhEjGt6lxffn69s/edit)

### Email
Subject: ```Important: NEAR Account Recovery Information```

Message:
```
Hi <account_name>,

This email contains your magic recovery link.

Keep this email safe, and DO NOT SHARE IT! 

You can recover your NEAR account by clicking the button below. 
We do not have access to this key, and cannot resend this email!

<Recover Account>
```

### Confirm Recovery Setup Copy
```
Confirm Recovery Setup
You should have received an email with a magic link. If you ever lose access to you account, simply click this link, and your account will be restored!

Please confirm receipt of this email at: <my@email.com>

**Confirm**

If you did not yet receive this email, or the above email address is incorrect click here to Re-enter your email and resend
```

### Restore Account
[Designs](https://yc3.s3.us-east-2.amazonaws.com/SS/Screen+Shot+2020-01-14+at+2.09.57+PM.png)

```
Restore

Select “Continue” to restore your account: @<account> in this browser.

NOTE: If this isn’t your preferred browser, we recommend copying the URL and completing this process in your browser of choice. 

<Continue>   <Copy URL>
```

**Comment by kcole16** [comment]
@vgrichina Thoughts on the above?

**Comment by kcole16** [comment]
@vgrichina Thoughts on the above?

**Comment by vgrichina** [comment]
1) "Email Confirm" screen should IMO communicate to user that they need to make sure they got recovery e-mail from us and that they need to keep it safe.

2) It's not clear how this will integrate with phone-based recovery. Non-tech people these days don't have e-mails, so it generally should be possible to specify either when signing up (like e.g. Facebook and Twitter do).

3) For higher security we might want to also confirm that e-mail/phone is still owned by user, i.e. after clicking the link we send another e-mail/SMS to user with security code (or one more link).

**Comment by kcole16** [comment]
1. Good point, will add

2. I'm open to keeping phone recovery if we have a good non-custodial way to do it. I thought the current plan was to remove it until we figure that out?

3. I like the idea of some extra verification during recovery, though it seems more likely an attacker gains access while the original user still has access (for email, at least).

**Comment by vgrichina** [comment]
2. Exactly the same approach to non-custodial as for e-mail works for phone as well. We just send SMS with secret link instead of e-mail with secret link.
3. At least for phones it's drastically different level: attacker needs to both sim clone and gain access to old messages, which are generally not correlated. For e-mail it's less effective I assume, but still possible to leak e-mail in a way that doesn't leak permanent access (e.g. if it's leaked by email delivery service or some app like LinkedIn scanning ones mailbox one time at sign up).

**Comment by vgrichina** [comment]
I think there are multiple dimensions for recovery and it makes sense for bigger picture to take them all into account.

1. Make sure it's easy for legitimate owner to recover account:
1.1. when they don't have account access from any device (this case grants complex flow with finding secret message, etc)
1.2. when they still have account access on at least one device (arguably far more common use case and it'll be painful to go through full flow every time). This one likely needs special flow (e.g. scan QR code or enter pin code displayed on one of devices) optimized for ease of use.
2. Make sure that NEAR doesn't have custody of the keys. Immediate solution is giving some secret to user that they need to keep. This is covered by seed phrase recovery + will be covered for SMS/e-mail recovery by sending message with secret that user needs to keep (i.e. basically what discussed here).
3. Make sure that it's hard for attacker to recover the account they don't own. I think generally it's harder to get continuous access to e-mail/phone vs just steal single message. For this reason I think we should still continue checking if e-mail/phone is still owned (i.e. get a message / enter code / press link to confirm – similar to how it currently works for phone).
4. Limit free giveaway of tokens (even if limited for gas). This works for phones and with some stretch for .edu e-mail addresses. We don't have solution for e-mail / seed-phrase accounts right now. CAPTCHA isn't a good solution, as is way too cheap to game (fractions of cent per one CAPTCHA). Potential solution is to require social account (with some restrictions like age, etc) instead of just e-mail. That is we e.g. require login with Twitter and then use associated e-mail to send recovery message.
