### ISSUE TITLE
Phone number recovery didn't work on .cn mirror

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-wallet#323]
**Problem**
Trying to recover my account on https://wallet.cn.nearprotocol.com but it just goes back to create new account after entering code

**Expected Behavior**
Account is recovered

**Steps to reproduce**

1. Go to https://wallet.cn.nearprotocol.com
2. Recover account
3. Enter account and phone number
4. Enter sms code 
5. Observe create account screen

**Comment by kcole16** [comment]
@marcinbodnar Can you take a look at this? Looks like it's still an issue in #291 as well

**Comment by marcinbodnar** [comment]
@kcole16 @vgrichina This change will fix main issue, but we still need to merge #291 so it will work as it supposed to. Because now after account recovery it will redirect you to URL from where you start wallet, so for example if you start with `/` it will redirect you to `/`, but if you start with `/create` it will redirect to `/create`. #291 fixes this problem.

**Comment by kcole16** [comment]
Closed by #324
