### ISSUE TITLE
Make "Setup Recovery Phrase" option more prominent

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-wallet#355]
We've received quite a bit of feedback that the manual recovery (seed phrase) option isn't prominent enough, and several users have missed it.

## Acceptance Criteria

- [ ] On desktop, manual recovery is side-by-side with email recovery
- [ ] `Setup Recovery Phrase` button is highlighted
- [ ] Manual recovery text is >=12pt font
- [ ] Mobile ok
- [ ] Tested

## Designs

[Figma Document](https://www.figma.com/file/BhrKSEYsyegyZ0jKsFJ3QR/NEAR-Wallet?node-id=20%3A10)

**Comment by Patrick1904** [comment]
@corwinharrell FYI

**Comment by corwinharrell** [comment]
At the time of this comment, it appears that the treatment for the initial option of manual backup is the same for both desktop and mobile (stacked within a single column). That being said, I'm looking into how we might make the option more prominent in both instances.

**Comment by corwinharrell** [comment]
With the upcoming changes to recovery, will the user be able to select multiple recovery options when they first set up a new account?

**Comment by kcole16** [comment]
> With the upcoming changes to recovery, will the user be able to select multiple recovery options when they first set up a new account (vs just a single option)? cc @kcole16

Current plan is to select a single option during setup, with the ability to add more later. Would like to keep initial setup as lightweight as possible.

**Comment by corwinharrell** [comment]
@kcole16 @Patrick1904 @vgrichina Ok, so taking into consideration some of the updates that are occurring around account recovery, I wanted to share [this exploration](https://www.figma.com/proto/BhrKSEYsyegyZ0jKsFJ3QR/NEAR-Wallet?node-id=5%3A205&viewport=923%2C170%2C0.3667091429233551&scaling=contain) and get some feedback.

These changes are certainly a little more involved than just visual emphasis, but I believe help to improve the experience in the following ways:

1. Show all options up front. In the current implementation, the switch between email/phone feels odd and is also easily missed. This exploration surfaces all security options so that the user knows right away what options they have available to them.

2. Allow the user to switch between basic security options and the completion of the attached fields without having to switch contexts or go back and forth between separate views.

3. Introduces a basic concept of "security levels". This is something we've briefly talked about, but I think would benefit us in gently pushing the user towards the more secure option of setting up a seed phrase. The `Basic` vs `Advanced` security language here is just placeholder. If this is direction we like, perhaps we can explore alternative language that may be more impactful.

The drawback of this exploration is obviously scope. If we think these improvements are not worth the increase in the scope of implementation, then we can settle for something that simply does a better job of visually emphasizing the recovery phrase option, and keep this in our back pockets. Just doing a little bit of thinking ahead here about how we might improve this initial experience.

**Comment by Patrick1904** [comment]
Overall I think this greatly improves clarity around recovery options available and grouping of levels of security.

Some notes:
- The sub headers takes up a lot of vertical height. Maybe skip the second sub header? 
- Curious about mobile. Let’s keep total height in mind for mobile design so that we can fit as much as possible on one screen to avoid risk of user missing seed phrase option.
- Are we going to offer a ‘setup later’ option too? [415](https://github.com/nearprotocol/near-wallet/issues/415#issue-571763874) @kcole16

**Comment by corwinharrell** [comment]
@Patrick1904 yeah will address the "Setup Later" option once we've nailed down the initial design for recovery method selection. Thanks for the feedback 👍If any of you have concerns re: scope here please let me know, otherwise it sounds like we want to continue down this path.

**Comment by corwinharrell** [comment]
Here's a link to the mobile version of the prototype. @Patrick1904 have omitted some of the subheadings to free up some vertical space, which now displays `onFocus`

[Mobile Prototype](https://www.figma.com/proto/BhrKSEYsyegyZ0jKsFJ3QR/NEAR-Wallet?node-id=20%3A10&viewport=946%2C-2280%2C0.48662543296813965&scaling=scale-down)

**Comment by Patrick1904** [comment]
Makes sense. Do you think our current 'country indicator' flag dropdown is unnecessary? We can just do the phone number formatting

**Comment by corwinharrell** [comment]
> Do you think our current 'country indicator' flag dropdown is unnecessary? We can just do the phone number formatting

@Patrick1904 does this play a role in validating the input?

**Comment by corwinharrell** [comment]
Summary points from conversation I had with @Patrick1904 around changes to phone number input:

- `onFocus` should prepend `+` to the input, which cannot be deleted, to indicate that a country code is necessary for validation

- Validation occurs after `x` seconds, and displays a generic input error message if the phone number is invalid (eg `Please input a valid phone number`) The reason validation should occur based on a time limit is because the user may not decide to click out of the input (`onBlur`), so we cannot depend on `onBlur` to trigger validation.

- Country drop-down `max-height` should be decreased

- If customizable, country drop-down placeholder icon should be replaced with a flag (shown below), and should also include a caret to indicate that it is a an interactive `select` element, and not just a static icon.

<img width="839" alt="Screen Shot 2020-03-10 at 2 29 00 PM" src="https://user-images.githubusercontent.com/5934188/76347582-45689e00-62dd-11ea-9dd8-f219cbc33627.png">

**Comment by Patrick1904** [comment]
@vgrichina @kcole16 @corwinharrell 

Here are some things to consider for phone input:

Complete feature list:
1. Make sure number is correct min length (varies a lot dep. on country)
2. Format number as user types (spaces, parenthesis, dashes, etc.)
3. Prepend with '+' if user misses it while typing number
4. Detect country based on input value and show corresponding country flag
5. Allow user to click on intl flag icon to select a country to prepend input value with selected country code

Our current package option:
https://www.npmjs.com/package/react-phone-number-input
1. Large size (4mb)

Most complete and flexible option:
https://www.npmjs.com/package/libphonenumber-js
1. Requires lots of customization
2. Large size (5mb)

Small package option:
https://www.npmjs.com/package/react-phone-input-2
1. Small size (400kb)
2. Does not do number 1 on feature list. We should probably confirm that recovery link was received with a code since I assume many users 'confirm' that they've received code without checking SMS first.

Minimal size/feature option:
1. No package
2. Only do number 3 on feature list
3. Have at least a minimum char for phone number
4. Not optimal for users who want to select a country code first
5. Similar to how Twitter does it except they check min. length depending on country and probably using libphonenumber-js or similar.

**Comment by kcole16** [comment]
@Patrick1904 I really like option 3 (react-phone-input-2) as it doesn't require users to know their country code (though most really should, at least outside US). And looks like we can lock the country code and `+` so it can't be accidentally deleted.

**Comment by Patrick1904** [comment]
> @Patrick1904 I really like option 3 (react-phone-input-2) as it doesn't require users to know their country code (though most really should, at least outside US). And looks like we can lock the country code and `+` so it can't be accidentally deleted.

Option 3 makes sense to me. Unless @vgrichina has any objections we'll move forward with that.

**Comment by corwinharrell** [comment]
@Patrick1904 I've added the link to the Figma document in the issue description.

**Comment by kcole16** [comment]
@corwinharrell Quick comments on the design:

We're considering:
1. Dropping the second paragraph in the copy under "Protect Your Account"
2. Removing the description from each individual option, and updating the top line copy to 
   - "Enter your email address or phone number and receive a magic link"
   - "Write down a 12 word recovery phrase and store it securely"

Made comments on the Figma as well. Thoughts?

**Comment by corwinharrell** [comment]
@kcole16 yeah let's keep discussion on specific design elements (pre-development) in Figma that way they are localized. Responded to all of them 👍

**Comment by Patrick1904** [comment]
> Summary points from conversation I had with @Patrick1904 around changes to phone number input:
> 
> * [ ]  `onFocus` should prepend `+` to the input, which **cannot be deleted**, to indicate that a country code is necessary for validation
> * [ ]  Validation occurs after `x` seconds, and displays a generic input error message if the phone number is invalid (eg `Please input a valid phone number`) The reason validation should occur based on a **time limit** is because the user may not decide to click out of the input (`onBlur`), so we cannot depend on `onBlur` to trigger validation.
> * [ ]  Country drop-down `max-height` should be **decreased**
> * [ ]  If customizable, country drop-down placeholder icon should be replaced with a flag (shown below), and should also include a caret to indicate that it is a an interactive `select` element, and not just a static icon.
> 
> <img alt="Screen Shot 2020-03-10 at 2 29 00 PM" width="839" src="https://user-images.githubusercontent.com/5934188/76347582-45689e00-62dd-11ea-9dd8-f219cbc33627.png">

@corwinharrell can you please share the 'no flag' icon in svg format
