### ISSUE TITLE
Username TLDs should match network

### ISSUE THREAD

**Issue by Patrick1904** [nearprotocol/near-wallet#407]
### Overview
To make it clear which network users are using, the TLD of usernames created through the wallet should match the network (except mainnet, which will be `.near`).

Mainnet -> `.near`
Testnet -> `.testnet`
Betanet -> `.betanet`
Devnet -> `.devnet`

**Comment by Patrick1904** [comment]
<img width="576" alt="Screen Shot 2020-02-24 at 11 53 48 AM" src="https://user-images.githubusercontent.com/24921205/75188976-16113900-5702-11ea-86d1-83e665c05a26.png">

Example from https://banter.pub/

**Comment by kcole16** [comment]
@vgrichina Can this be accomplished just by appending `.test` to `newAccountId` on this line? https://github.com/nearprotocol/near-contract-helper/blob/master/app.js#L64

Since we're using the @test account to create these already.

**Comment by kcole16** [comment]
@Patrick1904 Some thoughts on this:

1. Append `.test` to all usernames created with the faucet
2. Amend linkdrop so that users can create `.near` names using beta program apps like Flux, which we'll persist on mainnet

For now, we should just implement **1.**, but can consider **2.** in the next ~2-3 weeks as a promo.

**Comment by kcole16** [comment]
TODOs:
- Create an account on each network that matches the network name (see above)
- Set ACCOUNT_RECOVERY_KEY environment variable for each network instance on Render (near-contract-helper)
-  Set REACT_APP_ACCOUNT_ID_SUFFIX env variable in wallet
-  Set NETWORK_ID env variable in wallet
