### ISSUE TITLE
Recover account using phone-based recovery

### ISSUE THREAD

**Issue by eriktrautman** [nearprotocol/near-wallet#53]
As a user who has lost my keys or is using a new device, I want to recover my account using my telephone so I can continue along my merry way.

## Acceptance Criteria

- [x] After creating account in one browser, user can activate account on new browser using phone.
- [-] Human-readable error messages >> Pulled out into Issue #89 
- [ ] Works in Safari
- [ ] Works on android
- [ ] Works on iOS
- [ ] Tested

## Mockups

TODO @jakestutzman 

## Notes

what if user doesn't know their username either? Should they be able to look it up using their recovery phone?
what if user has linked multiple accounts to their phone number?

**Comment by vgrichina** [comment]
> what if user doesn't know their username either? Should they be able to look it up using their recovery phone?

it's a security trade off. I think the process to do that should be slightly more pain in the ass. 
if  we go with recover by phone only we'll have to send code (or at least pretend we did) for whatever number (even not registered) so that attacker cannot just mine numbers. This makes it slightly harder to recover for legit users if they mistype phone / forgot which one they used.


> what if user has linked multiple accounts to their phone number?

that's only a problem if you don't enter username
